config/routes.rb
Rails.application.routes.draw do
    root to: 'words#index'
    resources :words
    resources :keywords
    # post '/keywords(.:format)' => 'keywords#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/keyword.rb
class Keyword < ApplicationRecord
  validates :word, presence: true
end

app/models/word.rb
class Word < ApplicationRecord

  validates :firstword, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/keywords_controller.rb
class KeywordsController < ApplicationController
  def index
    @keywords = Keyword.order(updated_at: :desc).limit(1)
  end

  def new
    @keyword = Keyword.new
  end

  def create
    @keyword = Keyword.new
    if @keyword.save
      redirect_to action: :index
    end
  end


end

app/controllers/words_controller.rb
class WordsController < ApplicationController

  def index
    @words = Word.order(updated_at: :desc).limit(1)
    @word = Word.order(firstword: :desc).limit(1)
    @word = Word.new
  end

  def new
    @word = Word.new
  end

  def create
    @word = Word.new(word_params)
    # binding.pry
    if @word.save
    redirect_to action: :index
    end
  end

  def show
    @word = Word.find[params[:firstword]]
  end

  def rankup
    
  end


  private
  def word_params
    params.require(:word).permit!
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/keywords_helper.rb
module KeywordsHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/keywords/index.html.erb
<h1>入力画面</h1>
  <% @keywords.each do |word| %>
<ul class="lists">
  <div class='list'>
    <%= "検索するものは#{word.word} #{word.additionword}どす" %>
  </div>
</ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FormApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/words/index.html.erb
<h1>Hello World</h1>
<%= link_to "NEwページ", new_word_path%>


<% @words.each do |word| %>
<ul class="lists">
  <div class='list'>
    <%= "検索するものは#{word.firstword} #{word.secondword}どす" %>
    <% @test = word.firstword%>
  </div>
</ul>
<% end %>

<%= "#{params[:firstword]}と#{params[:secondword]}ですよ"%>

<%= form_with model: @word, local: true do |f| %>
<%= f.hidden_field :firstword, :value => @test %>
<%= f.text_field :secondword %>
<%= f.submit %>
<% end %>

app/views/words/new.html.erb
<%= form_with model: @word, local: true do |f| %>
<%= f.text_field :firstword %>
<%= f.text_field :secondword %>
<%= f.submit%>
<% end %>